name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov

      - name: Run tests with pytest and pytest-cov
        run: |
          python -m pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          slug: tlimao/freedom-lib
          token: ${{ secrets.CODECOV_TOKEN }}